id: I9899933C
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-18T22:25:12.681173'
last_modified: '2022-06-18T22:25:12.681189'
parser: null
source_metadata:
  title: The Great Treatise on the Stages of the Mantra Path by Tsong kha pa (1357–1419)
    (dGa ldan block print), colophon excerpt
  author: tsong kha pa blo bzang grags pa/
  description: 'Digital version 1.0 {Wylie}; WYLIE COPY of master xml (completed:
    2017-10-21); revised, thematic TEI markup'
  file_info:
  - 'Language: Wylie'
  - 'Coverage: Excerpt/Colophon'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:Sakya Research Centre (src)
  - Text input:Mathias Fermer (mf)
  - Editorial process:David Jackson (dj)
  - TEI Encoding:Sakya Research Centre
  - TEI Markup:Mathias Fermer (mf)
  - Revisions/Corrections:Mathias Fermer (mf)
  text_witnesses: https://sakyaresearch.org/sources/329
  bases:
    9bb7:
      title: The Great Treatise on the Stages of the Mantra Path by Tsong kha pa (1357–1419)
        (dGa ldan block print), colophon excerpt
      order: 1
      base_file: 9bb7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
